# Generated by Django 6.0.5 on 2026-06-30 05:28

import django.contrib.auth.models
import django.contrib.auth.validators
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('name', models.CharField(help_text='AI 总结出的简短名称，如"爱思助手"', max_length=128, verbose_name='页面名称')),
                ('html_content', models.TextField(help_text='完整的生成 HTML', verbose_name='HTML 内容')),
                ('task_id', models.UUIDField(db_index=True, help_text='生成该页面的 PageGenerationTask.task_id', verbose_name='关联任务 ID')),
                ('input_content', models.TextField(blank=True, default='', help_text='用户提交的原始需求描述', verbose_name='用户输入')),
                ('domain', models.CharField(blank=True, default=None, help_text='该页面绑定的域名，如"domain.com"。全局唯一，只能有一条记录占用。', max_length=255, null=True, unique=True, verbose_name='使用域名')),
            ],
            options={
                'verbose_name': '已保存页面',
                'verbose_name_plural': '已保存页面',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='PageGenerationTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('task_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, help_text='对外暴露的 UUID', unique=True, verbose_name='任务 ID')),
                ('session_key', models.CharField(blank=True, db_index=True, default='', help_text='关联的 Django session_key', max_length=64, verbose_name='会话标识')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '生成中'), ('completed', '已完成'), ('failed', '失败')], db_index=True, default='pending', max_length=16, verbose_name='状态')),
                ('progress', models.PositiveSmallIntegerField(default=0, help_text='0-100', verbose_name='进度')),
                ('message', models.TextField(blank=True, default='', help_text='当前阶段描述', verbose_name='状态消息')),
                ('input_content', models.TextField(blank=True, default='', verbose_name='用户输入')),
                ('prompt_snapshot', models.TextField(blank=True, default='', help_text='此次任务实际使用的提示词，便于回溯', verbose_name='提示词快照')),
                ('result_html', models.TextField(blank=True, default='', verbose_name='生成结果')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='错误信息')),
                ('page_name', models.CharField(blank=True, default='', help_text='AI 总结出的简短页面名称，如"爱思助手"', max_length=128, verbose_name='页面名称')),
            ],
            options={
                'verbose_name': '页面生成任务',
                'verbose_name_plural': '页面生成任务',
                'ordering': ['-create_time'],
            },
        ),
        migrations.CreateModel(
            name='SeoCloakRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='启用斗篷伪装')),
                ('search_engines', models.TextField(default='["google.", "bing.", "yahoo.", "yandex.", "duckduckgo.", "baidu.", "sogou.", "sm.", "360."]', help_text='JSON 数组，用于匹配 Referer 判断是否来自搜索引擎。', verbose_name='搜索引擎域名列表')),
                ('spider_keywords', models.TextField(default='["googlebot", "bingbot", "baiduspider", "yandexbot", "duckduckbot", "sogou", "sosospider", "360spider", "slurp", "mj12bot", "ahrefsbot", "semrushbot", "seznambot", "dotbot", "crawler", "spider", "bot"]', help_text='JSON 数组，用于匹配 User-Agent 判断是否为爬虫。', verbose_name='爬虫标识关键字')),
                ('spider_action', models.CharField(choices=[('pass_through', '放行（返回正常内容）'), ('show_seo', '展示 SEO 优化内容'), ('show_cloak', '展示伪装内容'), ('redirect', '重定向到指定 URL'), ('block', '阻止访问')], default='show_seo', help_text='检测到是爬虫/蜘蛛时执行的操作', max_length=20, verbose_name='爬虫行为')),
                ('search_action', models.CharField(choices=[('pass_through', '放行（返回正常内容）'), ('show_seo', '展示 SEO 优化内容'), ('show_cloak', '展示伪装内容'), ('redirect', '重定向到指定 URL'), ('block', '阻止访问')], default='show_cloak', help_text='真实用户从搜索引擎跳转来时执行的操作', max_length=20, verbose_name='搜索引擎用户行为')),
                ('direct_action', models.CharField(choices=[('pass_through', '放行（返回正常内容）'), ('show_seo', '展示 SEO 优化内容'), ('show_cloak', '展示伪装内容'), ('redirect', '重定向到指定 URL'), ('block', '阻止访问')], default='pass_through', help_text='真实用户直接访问（非搜索引擎来源）时执行的操作', max_length=20, verbose_name='直接访问行为')),
                ('redirect_status_code', models.IntegerField(choices=[(301, '301 — 301 Moved Permanently'), (302, '302 — 302 Found'), (303, '303 — 303 See Other'), (307, '307 — 307 Temporary Redirect'), (308, '308 — 308 Permanent Redirect')], default=302, help_text='执行 redirect 行为时使用的 HTTP 状态码', verbose_name='重定向状态码')),
                ('spider_redirect_url', models.CharField(blank=True, default='', help_text='爬虫命中 redirect 时的目标 URL（需完整 URL，如 https://example.com）', max_length=500, verbose_name='爬虫重定向 URL')),
                ('search_redirect_url', models.CharField(blank=True, default='', help_text='搜索引擎用户命中 redirect 时的目标 URL', max_length=500, verbose_name='搜索引擎用户重定向 URL')),
                ('direct_redirect_url', models.CharField(blank=True, default='', help_text='直接访问命中 redirect 时的目标 URL', max_length=500, verbose_name='直接访问重定向 URL')),
                ('seo_content', models.TextField(blank=True, default='', help_text='展示给爬虫的 HTML 内容。留空则返回原始页面。', verbose_name='SEO 优化内容')),
                ('cloak_content', models.TextField(blank=True, default='', help_text='展示给搜索引擎用户的 HTML 内容。留空则返回原始页面。', verbose_name='伪装内容')),
                ('whitelist_paths', models.TextField(blank=True, default='', help_text='不受斗篷伪装影响的路径，每行一条（支持前缀匹配，如 /api/）', verbose_name='白名单路径')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '斗篷伪装规则',
                'verbose_name_plural': '斗篷伪装规则',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('statistics_code', models.TextField(blank=True, default='', help_text='用于存放全局统计代码、第三方分析脚本等内容，会在全站页面底部引入', verbose_name='全局代码统计')),
                ('is_active', models.BooleanField(default=True, help_text='关闭后全局统计代码将不会在页面中输出', verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '网站设置',
                'verbose_name_plural': '网站设置',
            },
        ),
        migrations.CreateModel(
            name='SpiderLogConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('log_mode', models.CharField(choices=[('all', '全部访问 — 记录所有请求（爬虫 + 真人）'), ('spider_only', '仅爬虫 — 只记录被识别为爬虫的访问'), ('disabled', '关闭 — 不记录任何访问')], default='all', help_text='控制 SpiderLogMiddleware 记录哪些访问', max_length=20, verbose_name='记录模式')),
            ],
            options={
                'verbose_name': '蜘蛛日志配置',
                'verbose_name_plural': '蜘蛛日志配置',
            },
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('category', models.CharField(choices=[('page_generation', '页面生成'), ('page_optimization', '页面优化'), ('custom', '自定义')], db_index=True, default='page_generation', help_text='按用途分组，调用时按分类查找', max_length=64, verbose_name='提示词分类')),
                ('name', models.CharField(help_text='人类可读的名称，如"通用页面生成 v3"', max_length=128, verbose_name='提示词名称')),
                ('content', models.TextField(help_text='完整的提示词文本，会作为 system_prompt 发送给 AI', verbose_name='提示词内容')),
                ('version', models.PositiveIntegerField(default=1, help_text='同一 category 下递增；创建时自动 = max+1', verbose_name='版本号')),
                ('is_active', models.BooleanField(default=True, help_text='关闭后该提示词不会被 AI 调用使用', verbose_name='是否启用')),
                ('description', models.TextField(blank=True, default='', help_text='本次更新的说明，例如"调整了输出格式要求"', verbose_name='变更说明')),
            ],
            options={
                'verbose_name': '提示词',
                'verbose_name_plural': '提示词',
                'ordering': ['category', '-version'],
                'indexes': [models.Index(fields=['category', 'is_active', '-version'], name='XiaoYingAdm_categor_188e8e_idx')],
            },
        ),
        migrations.CreateModel(
            name='SpiderAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('ip', models.GenericIPAddressField(help_text='支持 IPv4 / IPv6', verbose_name='访问 IP')),
                ('user_agent', models.TextField(help_text='完整 UA 字符串', verbose_name='User-Agent')),
                ('spider_name', models.CharField(blank=True, default='', help_text='识别出的爬虫名（如 Googlebot / Baiduspider）；非爬虫留空', max_length=64, verbose_name='爬虫名')),
                ('path', models.CharField(help_text='请求路径（不含 query string）', max_length=500, verbose_name='访问路径')),
                ('method', models.CharField(default='GET', max_length=10, verbose_name='HTTP 方法')),
                ('referer', models.CharField(blank=True, default='', max_length=500, verbose_name='来源 URL')),
                ('status_code', models.IntegerField(blank=True, help_text='由中间件在响应阶段回填', null=True, verbose_name='响应状态码')),
                ('response_size', models.IntegerField(blank=True, help_text='由中间件在响应阶段回填（len(response.content)）', null=True, verbose_name='响应字节数')),
            ],
            options={
                'verbose_name': '蜘蛛访问日志',
                'verbose_name_plural': '蜘蛛访问日志',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['-create_time'], name='idx_log_time'), models.Index(fields=['ip'], name='idx_log_ip'), models.Index(fields=['spider_name'], name='idx_log_spider')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, default='', max_length=20, verbose_name='手机号')),
                ('avatar', models.URLField(blank=True, default='', verbose_name='头像')),
                ('bio', models.TextField(blank=True, default='', verbose_name='个人简介')),
                ('is_verified', models.BooleanField(default=False, verbose_name='是否已验证')),
                ('extra_data', models.JSONField(blank=True, default=dict, verbose_name='扩展数据')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'xiaoying_admin_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
