# Generated by Django 6.0.5 on 2026-06-30 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XiaoYingAdmin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('registration_enabled', models.BooleanField(default=False, help_text='开启后，用户可通过注册页面自行注册账号', verbose_name='开放注册')),
                ('default_group_id', models.IntegerField(blank=True, default=None, help_text='新注册用户自动加入的用户组 ID（预留），为空则不自动加入', null=True, verbose_name='默认用户组')),
                ('extra_config', models.JSONField(blank=True, default=dict, help_text='JSON 格式扩展配置，用于后续扩展', verbose_name='扩展配置')),
            ],
            options={
                'verbose_name': '用户系统配置',
                'verbose_name_plural': '用户系统配置',
            },
        ),
    ]
