# Generated by Django 6.0.5 on 2026-06-30 05:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XiaoYingAdmin', '0002_userconfig'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoginLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(help_text='登录时提交的用户名（冗余存储）', max_length=150, verbose_name='登录账号')),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('status', models.CharField(choices=[('success', '登录成功'), ('failed_disabled', '用户已禁用'), ('failed_password', '密码错误'), ('failed_not_found', '用户不存在'), ('failed_inactive', '用户未激活')], db_index=True, max_length=30, verbose_name='登录结果')),
                ('error_msg', models.CharField(blank=True, default='', max_length=255, verbose_name='错误信息')),
                ('login_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='登录时间')),
                ('session_key', models.CharField(blank=True, default='', help_text='登录成功后的 session key', max_length=40, verbose_name='Session Key')),
                ('user', models.ForeignKey(blank=True, default=None, help_text='关联的后台用户，用户被删后此字段置空', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='关联用户')),
            ],
            options={
                'verbose_name': '登录日志',
                'verbose_name_plural': '登录日志',
                'db_table': 'xiaoying_admin_login_log',
                'ordering': ['-login_time'],
            },
        ),
    ]
