# Generated by Django 6.0.5 on 2026-06-30 06:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XiaoYingAdmin', '0003_loginlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('username', models.CharField(db_index=True, help_text='操作用户名（冗余存储）', max_length=150, verbose_name='用户名')),
                ('action', models.CharField(choices=[('create', '创建'), ('update', '修改'), ('delete', '删除'), ('login', '登录'), ('logout', '登出'), ('export', '导出'), ('other', '其他')], db_index=True, max_length=20, verbose_name='操作类型')),
                ('target_type', models.CharField(blank=True, db_index=True, default='', help_text='如 User、SeoCloakRule、SiteSettings 等', max_length=100, verbose_name='操作对象类型')),
                ('target_id', models.CharField(blank=True, default='', help_text='操作对象的 primary key', max_length=50, verbose_name='操作对象 ID')),
                ('target_repr', models.CharField(blank=True, default='', help_text='操作对象的文字描述，如 "用户 admin"', max_length=255, verbose_name='操作描述')),
                ('detail', models.JSONField(blank=True, default=None, help_text='JSON 格式，可存变更字段、旧值/新值等', null=True, verbose_name='详细数据')),
                ('method', models.CharField(blank=True, default='', max_length=10, verbose_name='HTTP 方法')),
                ('path', models.CharField(blank=True, default='', max_length=500, verbose_name='请求路径')),
                ('ip_address', models.GenericIPAddressField(blank=True, default=None, null=True, verbose_name='IP 地址')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='User-Agent')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='操作时间')),
                ('user', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='操作用户')),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'xiaoying_admin_operation_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
