# Generated by Django 6.0.5 on 2026-06-30 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XiaoYingAdmin', '0004_operationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('rule_type', models.CharField(choices=[('ip_block', 'IP 黑名单'), ('page_block', '路径黑名单'), ('ip_whitelist', 'IP 白名单')], max_length=20, verbose_name='规则类型')),
                ('value', models.CharField(help_text='IP 地址（如 192.168.1.1）或路径（如 /admin/），路径支持前缀匹配', max_length=500, verbose_name='匹配值')),
                ('is_active', models.BooleanField(default=True, verbose_name='启用')),
                ('response_type', models.CharField(choices=[('forbidden', '默认拒绝（403）'), ('custom_html', '自定义 HTML'), ('custom_js', '自定义 JS'), ('redirect', '重定向')], default='forbidden', max_length=20, verbose_name='拦截响应类型')),
                ('custom_content', models.TextField(blank=True, default='', help_text='response_type 为 custom_html 时填写 HTML；为 custom_js 时填写 JS 代码', verbose_name='自定义内容')),
                ('redirect_url', models.CharField(blank=True, default='', help_text='response_type 为 redirect 时填写目标 URL', max_length=500, verbose_name='重定向 URL')),
                ('description', models.CharField(blank=True, default='', max_length=255, verbose_name='备注描述')),
                ('hit_count', models.IntegerField(default=0, help_text='该规则被触发的总次数', verbose_name='命中次数')),
                ('last_hit_at', models.DateTimeField(blank=True, null=True, verbose_name='最后命中时间')),
            ],
            options={
                'verbose_name': '防火墙规则',
                'verbose_name_plural': '防火墙规则',
                'ordering': ['-create_time'],
                'indexes': [models.Index(fields=['rule_type', 'is_active'], name='idx_fw_type_active')],
            },
        ),
    ]
