# Generated by Django 6.0.5 on 2026-06-30 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XiaoYingAdmin', '0005_firewallrule'),
    ]

    operations = [
        migrations.AddField(
            model_name='spiderlogconfig',
            name='ignore_paths',
            field=models.TextField(blank=True, default='', help_text='一行一个路径前缀，匹配的请求不会被记录到蜘蛛日志中', verbose_name='忽略路径'),
        ),
    ]
