# Generated by Django 6.0.5 on 2026-07-01 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('XiaoYingAdmin', '0006_spiderlogconfig_ignore_paths'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedpage',
            name='domains',
            field=models.JSONField(blank=True, default=list, help_text='支持多个域名及 *. 通配符，如 ["example.com", "*.example.com"]', verbose_name='绑定域名列表'),
        ),
        migrations.AlterField(
            model_name='generatedpage',
            name='domain',
            field=models.CharField(blank=True, default=None, help_text='已废弃，请使用 domains 字段。仅用于兼容旧数据。', max_length=255, null=True, verbose_name='使用域名（旧）'),
        ),
    ]
